---
- name: Install packages (debian)
  when: ansible_os_family == 'Debian'
  package: name={{ item }} state=latest
  with_items:
    - python-dev
    - libffi-dev
    - openssl
    - libssl-dev
    - supervisor
    - mongodb
  become: True

- name: Install packages (rhel)
  when: ansible_os_family != 'Debian'
  package: name={{ item }} state=latest
  with_items:
    - python-devel
    - libffi-devel
    - openssl
    - openssl-devel
    - supervisor
  become: True

- name: Create helga user
  user: name=helga comment="Helga"

- name: Create helga directory
  file: path={{ helga_path }} state=directory mode=0755

- name: Generate settings file
  template: src=settings.py.j2
            dest={{ helga_path }}settings.py
            owner=helga
            group=helga
            mode=640

- name: Copy requirements.txt
  template: src=requirements.txt.j2
            dest={{ helga_path }}requirements.txt
            owner=helga
            group=helga
            mode=640

- name: pip install requirements.txt
  pip: requirements={{ helga_path }}requirements.txt
  become: True

- name: Generate supervisord file (debian)
  when: ansible_os_family == 'Debian'
  template: src=helga.ini.j2
          dest=/etc/supervisor/conf.d/helga.ini
          owner=root
          group=root
          mode=640

- name: Generate supervisord file (rhel)
  when: ansible_os_family != 'Debian'
  template: src=helga.ini.j2
          dest=/etc/supervisord.d/helga.ini
          owner=root
          group=root
          mode=640

- name: Restart supervisor
  service: name=supervisor state=restarted
