---
- include: packages.yml

- name: Create helga user
  user: name=helga comment="Helga"

- name: Check helga directory
  stat:
    path: "{{ helga_path }}"
  register: helga_dir_stat_result

- name: Create helga directory
  file: path={{ helga_path }} state=directory mode=0755
  when: helga_dir_stat_result.stat.exists == False

- include: settings.yml

- include: requirements.yml

- name: Generate supervisord file (debian)
  when: ansible_os_family == 'Debian'
  template: src=helga.conf.j2
          dest=/etc/supervisor/conf.d/helga.conf
          owner=root
          group=root
          mode=640
  notify:
  - Read helga

- name: Generate supervisord file (rhel)
  when: ansible_os_family != 'Debian'
  template: src=helga.conf.j2
          dest=/etc/supervisord.d/helga.conf
          owner=root
          group=root
          mode=640
  notify:
  - Read helga
