---
- name: Supervisor changed
  service:
    name: supervisor
    state: restarted
    enabled: yes
  become: True

- name: Read helga
  supervisorctl:
    name: helga
    state: present
  become: True

- name: Restart helga
  supervisorctl:
    name: helga
    state: restarted
  become: True
